-- MySQL Script generated by MySQL Workbench
-- Tue May  2 19:00:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_lib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_lib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_lib` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_lib` ;

-- -----------------------------------------------------
-- Table `db_lib`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `photo` VARCHAR(512) NULL DEFAULT NULL,
  `biography` VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `description` VARCHAR(2048) NULL DEFAULT NULL,
  `photo` VARCHAR(512) NULL DEFAULT NULL,
  `avg_rating` DOUBLE NULL DEFAULT NULL,
  `date_of_creation` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`author_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`author_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ab_author_idx` (`author_id` ASC) VISIBLE,
  INDEX `FK_ab_book_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK_ab_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `db_lib`.`author` (`id`),
  CONSTRAINT `FK_ab_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_lib`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`mark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`role_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `date_of_registration` DATETIME NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_lib`.`role_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`featured_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`featured_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `date_of_add` DATETIME NOT NULL,
  `mark_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_fb_mark_idx` (`mark_id` ASC) VISIBLE,
  INDEX `FK_fb_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_fb_book_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK_fb_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_lib`.`book` (`id`),
  CONSTRAINT `FK_fb_mark`
    FOREIGN KEY (`mark_id`)
    REFERENCES `db_lib`.`mark` (`id`),
  CONSTRAINT `FK_fb_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_lib`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`genre_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`genre_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_gb_book_idx` (`book_id` ASC) VISIBLE,
  INDEX `FK_gb_genre_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `FK_gb_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_lib`.`book` (`id`),
  CONSTRAINT `FK_gb_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `db_lib`.`genre` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date_of_creation` DATETIME NOT NULL,
  `name` VARCHAR(256) NULL DEFAULT NULL,
  `content` VARCHAR(4096) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_note_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_note_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_lib`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `date_of_creation` DATETIME NOT NULL,
  `rating` INT NOT NULL,
  `content` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_review_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_review_book_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `FK_review_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `db_lib`.`book` (`id`),
  CONSTRAINT `FK_review_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_lib`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_lib`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lib`.`like` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `review_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_like_review_idx` (`review_id` ASC) VISIBLE,
  INDEX `FK_like_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_like_review`
    FOREIGN KEY (`review_id`)
    REFERENCES `db_lib`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_like_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_lib`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db_lib`;

DELIMITER $$
USE `db_lib`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_lib`.`review_AFTER_INSERT`
AFTER INSERT ON `db_lib`.`review`
FOR EACH ROW
BEGIN
	update `book` set `book`.`avg_rating` = (select avg(r.rating) from review as r where `book`.`id` = r.`book_id`) where `book`.`id` = new.`book_id` ;
END$$

USE `db_lib`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_lib`.`review_AFTER_UPDATE`
AFTER UPDATE ON `db_lib`.`review`
FOR EACH ROW
BEGIN
	update `book` set `book`.`avg_rating` = (select avg(r.rating) from review as r where `book`.`id` = r.`book_id`) where `book`.`id` = new.`book_id` ;
END$$

USE `db_lib`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `db_lib`.`review_AFTER_DELETE`
AFTER DELETE ON `db_lib`.`review`
FOR EACH ROW
BEGIN
	update `book` set `book`.`avg_rating` = (select avg(r.rating) from review as r where `book`.`id` = r.`book_id`) where `book`.`id` = old.`book_id` ;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
